name: banca_creditos
description: "A new Flutter project for simulate credits in a bank."
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^13.1.0
  flutter_riverpod: ^2.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8


flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/Product-Sans-Bold.ttf
        - asset: fonts/Product-Sans-Bold-Italic.ttf
        - asset: fonts/Product-Sans-Italic.ttf
        - asset: fonts/Product-Sans-Regular.ttf

  assets:
    - assets/

